name: Go Test

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    services:
      redis:
        image: redis:2.8
        ports:
          - "6379:6379"
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build ./...

      - name: Test
        env:
          REDIS_URL: redis://localhost:6379
        run: go test -v -race  ./...

